name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  CLUSTER: template-apps
  REGION: us-east-1
  NAMESPACE: apps-template

jobs:
  create-cluster:
    name: Create EKS Cluster
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}

      - name: Install eksctl
        run: |
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
          # (Optional) Verify checksum
          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        run: |
          eksctl create cluster -f <(echo '
            apiVersion: eksctl.io/v1alpha5
            kind: ClusterConfig
            
            metadata:
              name: ${{env.CLUSTER}}
              region: ${{env.REGION}}
            
            fargateProfiles:
              - name: fp-$CLUSTER-$NAMESPACE
                selectors:
                  - namespace: $NAMESPACE
              ')
