name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  CLUSTER: briklabs-eks-cluster
  REGION: us-east-1
  NAMESPACE: apps-template
  NODE_TYPE: t2-micro
  NODES_MIN: 1
  NODES_MAX: 5

jobs:
  create-cluster:
    name: Create EKS Cluster
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}

      - name: Install eksctl
        run: |
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
          # (Optional) Verify checksum
          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster
        run: |
          #!/bin/bash
          CLUSTER_EXISTS=$(eksctl get cluster --region ${{env.REGION}} --name ${{env.CLUSTER}} --output json 2>/dev/null)
          if [ -z "$CLUSTER_EXISTS" ]; then
            echo "Cluster does not exist. Creating cluster..."
            eksctl create cluster --name ${{env.CLUSTER}} --region ${{env.REGION}}
            echo "Cluster created successfully."
          else
            echo "Cluster already exists. Skipping cluster creation."
          fi
          NODEGROUP_EXISTS=$(eksctl get nodegroup --region ${{env.REGION}} --cluster ${{env.CLUSTER}} --name ng-${{env.NAMESPACE}} --output json 2>/dev/null)
          if [ -z "$NODEGROUP_EXISTS" ]; then
            echo "Nodegroup does not exist. Creating nodegroup..."
            eksctl create nodegroup --cluster ${{env.CLUSTER}} --region ${{env.REGION}} --name ng-${{env.NAMESPACE}} --node-type ${{env.NODE_TYPE}} --nodes-min ${{env.NODES_MIN}} --nodes-max ${{env.NODES_MAX}}
            echo "Nodegroup created successfully."
          else
            echo "Nodegroup already exists. Skipping nodegroup creation."
          fi          
